import type {
  TeamMember,
  OKR,
  Sprint,
  Meeting,
  Retrospective,
} from '../types';

export const teamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Khaled Baraya',
    role: 'Engineering Manager',
    email: 'khaled@teampulse.dev',
    avatar_color: '#8b5cf6',
    skills: ['System Design', 'Python', 'Leadership', 'Agile'],
    status: 'available',
  },
  {
    id: 'tm-2',
    name: 'Sara Mansour',
    role: 'Senior Frontend Engineer',
    email: 'sara@teampulse.dev',
    avatar_color: '#06b6d4',
    skills: ['React', 'TypeScript', 'CSS', 'Figma'],
    status: 'available',
  },
  {
    id: 'tm-3',
    name: 'Omar Farouk',
    role: 'Backend Lead',
    email: 'omar@teampulse.dev',
    avatar_color: '#10b981',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis'],
    status: 'busy',
  },
  {
    id: 'tm-4',
    name: 'Lina Haddad',
    role: 'UI/UX Designer',
    email: 'lina@teampulse.dev',
    avatar_color: '#f59e0b',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    status: 'available',
  },
  {
    id: 'tm-5',
    name: 'Ahmed Nasser',
    role: 'DevOps Engineer',
    email: 'ahmed@teampulse.dev',
    avatar_color: '#ef4444',
    skills: ['Docker', 'Kubernetes', 'Terraform', 'CI/CD'],
    status: 'busy',
  },
  {
    id: 'tm-6',
    name: 'Noor Al-Rashid',
    role: 'QA Engineer',
    email: 'noor@teampulse.dev',
    avatar_color: '#ec4899',
    skills: ['Cypress', 'Playwright', 'Test Strategy', 'API Testing'],
    status: 'away',
  },
];

export const okrs: OKR[] = [
  {
    id: 'okr-1',
    title: 'Improve Platform Reliability',
    owner_id: 'tm-3',
    quarter: 3,
    year: 2025,
    status: 'on_track',
    key_results: [
      {
        id: 'kr-1a',
        title: 'Reduce P1 incident response time to under 5 minutes',
        current_value: 5.2,
        target_value: 5.0,
        unit: 'minutes',
        status: 'on_track',
      },
      {
        id: 'kr-1b',
        title: 'Achieve 99.95% uptime across all production services',
        current_value: 99.91,
        target_value: 99.95,
        unit: '%',
        status: 'on_track',
      },
      {
        id: 'kr-1c',
        title: 'Reduce error rate in critical API endpoints by 60%',
        current_value: 52,
        target_value: 60,
        unit: '%',
        status: 'at_risk',
      },
    ],
  },
  {
    id: 'okr-2',
    title: 'Accelerate Feature Delivery',
    owner_id: 'tm-1',
    quarter: 3,
    year: 2025,
    status: 'on_track',
    key_results: [
      {
        id: 'kr-2a',
        title: 'Increase sprint velocity from 34 to 48 story points',
        current_value: 42,
        target_value: 48,
        unit: 'points',
        status: 'on_track',
      },
      {
        id: 'kr-2b',
        title: 'Reduce average PR review cycle time to under 4 hours',
        current_value: 5.1,
        target_value: 4.0,
        unit: 'hours',
        status: 'at_risk',
      },
      {
        id: 'kr-2c',
        title: 'Ship 3 major features to production this quarter',
        current_value: 2,
        target_value: 3,
        unit: 'features',
        status: 'on_track',
      },
    ],
  },
  {
    id: 'okr-3',
    title: 'Enhance Developer Experience',
    owner_id: 'tm-5',
    quarter: 3,
    year: 2025,
    status: 'at_risk',
    key_results: [
      {
        id: 'kr-3a',
        title: 'Reduce CI/CD pipeline duration to under 8 minutes',
        current_value: 10.5,
        target_value: 8.0,
        unit: 'minutes',
        status: 'at_risk',
      },
      {
        id: 'kr-3b',
        title: 'Achieve 80% developer satisfaction score in internal survey',
        current_value: 68,
        target_value: 80,
        unit: '%',
        status: 'behind',
      },
      {
        id: 'kr-3c',
        title: 'Onboard 100% of services to new observability platform',
        current_value: 5,
        target_value: 8,
        unit: 'services',
        status: 'at_risk',
      },
    ],
  },
];

export const sprints: Sprint[] = [
  {
    id: 'sp-8',
    name: 'Sprint 8',
    start_date: '2025-05-19',
    end_date: '2025-06-01',
    velocity: 34,
    planned_points: 38,
    completed_points: 34,
  },
  {
    id: 'sp-9',
    name: 'Sprint 9',
    start_date: '2025-06-02',
    end_date: '2025-06-15',
    velocity: 37,
    planned_points: 40,
    completed_points: 37,
  },
  {
    id: 'sp-10',
    name: 'Sprint 10',
    start_date: '2025-06-16',
    end_date: '2025-06-29',
    velocity: 42,
    planned_points: 44,
    completed_points: 42,
  },
  {
    id: 'sp-11',
    name: 'Sprint 11',
    start_date: '2025-06-30',
    end_date: '2025-07-13',
    velocity: 45,
    planned_points: 46,
    completed_points: 45,
  },
];

export const meetings: Meeting[] = [
  {
    id: 'mtg-1',
    title: 'Sprint 11 Planning',
    date: '2025-06-30T10:00:00',
    type: 'sprint',
    attendee_ids: ['tm-1', 'tm-2', 'tm-3', 'tm-4', 'tm-5', 'tm-6'],
    agenda_items: [
      'Review Sprint 10 outcomes and carryover items',
      'Estimate and commit to Sprint 11 backlog',
      'Assign ownership for high-priority stories',
      'Discuss cross-team dependency on Auth service migration',
    ],
    action_items: [
      { id: 'ai-1', text: 'Break down Auth migration epic into sub-tasks', assignee_id: 'tm-3', due_date: '2025-07-02', completed: true },
      { id: 'ai-2', text: "Update capacity plan with Noor's PTO", assignee_id: 'tm-1', due_date: '2025-07-01', completed: true },
      { id: 'ai-3', text: 'Draft technical spec for real-time notifications', assignee_id: 'tm-2', due_date: '2025-07-04', completed: false },
    ],
    notes: 'Team agreed to limit WIP to 3 items per developer. Auth migration is critical path — Omar to coordinate with Platform team. Velocity target: 46 points.',
  },
  {
    id: 'mtg-2',
    title: '1-on-1: Khaled & Sara',
    date: '2025-07-07T14:00:00',
    type: 'one_on_one',
    attendee_ids: ['tm-1', 'tm-2'],
    agenda_items: [
      'Career growth discussion — path to Staff Engineer',
      'Review frontend architecture RFC feedback',
      'Discuss conference talk proposal for ReactConf',
    ],
    action_items: [
      { id: 'ai-4', text: 'Submit Staff Engineer promotion packet draft', assignee_id: 'tm-2', due_date: '2025-07-14', completed: false },
      { id: 'ai-5', text: 'Connect Sara with Staff engineers in Platform for mentorship', assignee_id: 'tm-1', due_date: '2025-07-11', completed: false },
    ],
    notes: 'Sara is ready for increased scope. Discussed leading the Design System migration as a Staff-level project. ReactConf abstract deadline is July 20.',
  },
  {
    id: 'mtg-3',
    title: 'Sprint 10 Review & Demo',
    date: '2025-06-29T15:00:00',
    type: 'sprint',
    attendee_ids: ['tm-1', 'tm-2', 'tm-3', 'tm-5', 'tm-6'],
    agenda_items: [
      'Demo: Real-time dashboard data streaming (Sara)',
      'Demo: Automated canary deployment pipeline (Ahmed)',
      'Review sprint metrics — 42/44 points completed',
      'Stakeholder feedback collection',
    ],
    action_items: [
      { id: 'ai-6', text: 'File bug for dashboard WebSocket reconnection edge case', assignee_id: 'tm-6', due_date: '2025-07-01', completed: true },
      { id: 'ai-7', text: 'Schedule canary pipeline walkthrough for Platform team', assignee_id: 'tm-5', due_date: '2025-07-03', completed: true },
    ],
    notes: 'Stakeholders impressed with dashboard streaming performance. Canary deployment pipeline approved for production rollout. Two minor bugs identified during demo — both non-blocking.',
  },
];

export const retrospectives: Retrospective[] = [
  {
    id: 'retro-1',
    sprint_id: 'sp-11',
    date: '2025-07-13',
    items: [
      { id: 'ri-1', category: 'went_well', text: 'CI/CD pipeline improvements reduced average deploy time by 40%', votes: 5, author_id: 'tm-5' },
      { id: 'ri-2', category: 'went_well', text: 'Pair programming sessions significantly improved knowledge sharing across backend and frontend', votes: 4, author_id: 'tm-2' },
      { id: 'ri-3', category: 'went_well', text: 'New automated canary deployments caught a critical regression before it hit production', votes: 6, author_id: 'tm-5' },
      { id: 'ri-4', category: 'went_well', text: 'Sprint velocity improved for the 4th consecutive sprint — team is hitting its stride', votes: 3, author_id: 'tm-1' },
      { id: 'ri-5', category: 'to_improve', text: 'Need more consistent code review coverage — some PRs waited 2+ days for review', votes: 4, author_id: 'tm-3' },
      { id: 'ri-6', category: 'to_improve', text: 'Flaky integration tests in the payments module are eroding confidence in the test suite', votes: 5, author_id: 'tm-6' },
      { id: 'ri-7', category: 'to_improve', text: 'Cross-team dependency on Auth service migration caused 3 days of blocked work', votes: 3, author_id: 'tm-3' },
      { id: 'ri-8', category: 'action', text: 'Implement a PR review rotation schedule to guarantee <24h first review', votes: 4, author_id: 'tm-1' },
      { id: 'ri-9', category: 'action', text: 'Dedicate 2 story points per sprint to fixing flaky tests', votes: 3, author_id: 'tm-6' },
      { id: 'ri-10', category: 'action', text: 'Set up weekly sync with Platform team to unblock cross-team dependencies early', votes: 2, author_id: 'tm-1' },
    ],
  },
];
